// This file is auto-generated by get-audio-duration.js
import audioDuration from './audioDuration.json';

export const AUDIO_DURATION_SECONDS = audioDuration.duration;
export const FPS = 30;
export const AUDIO_DURATION_FRAMES = Math.ceil(AUDIO_DURATION_SECONDS * FPS);
